### ISSUE TITLE
Error:(36, 28) No resource found that matches the given name (at 'value' with value '@string/fabric_api_key').

### ISSUE THREAD

**Issue by plastic-kai** [naman14/AlgorithmVisualizer-Android#2]
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/kaiwang/Library/Android/sdk/build-tools/24.0.3/aapt'' finished with non-zero exit value 1

**Comment by naman14** [comment]
Replace @string/fabric_api_key with any string you want. Crashlytics is disabled for debug builds so it should be able to build without any issues then. If you are going for a release apk, then you need to enter your own fabric API key there.

**Comment by plastic-kai** [comment]
add this to string.xml:

`
    <string name="fabric_api_key">any string you like</string>
    <string name="play_billing_license_key">i do what i want</string>`

and its good to go.
